name: Chunky
game_type: jeopardy
description: I Think You Should Leave Trivia
categories:
  - name: Fashion Police
    questions:
      - question: This high-end menswear brand can be found at the Shops at the Creek
        answer: Dan Flashes
        points: 100
      - question: These jeans may have a 54 inch waist and 10 inch inseam
        answer: Chode Jeans
        points: 200
      - question: Worn by rappers, this apparel item has a characteristic spatter pattern.
        answer: Calico Cut Pants
        points: 300
      - question: This shirt, not a joke, is designed for men whose shirts get stuck on their bellies
        answer: TC Tuggers
        points: 400
      - question: This hat adorns the heads of mobsters in this year's hot new Gangster movie
        answer: Stanzo Brand Fedoras
        points: 500
  - name: It's Dinner Time
    questions:
      - question: It's safe to eat paper, but it's not safe to eat this item
        answer: Mud Pie
        points: 100
      - question: This food item has to be shared equally, you can't just eat all the ones with the meat and cheese
        answer: Fully Loaded Nachos
        points: 200
      - question: IT'S A CHUNKY
        answer: HE IS GOBBLING UP YOUR POINTS
        points: 300
        actual_points: -300
      - question: This food item has been banned from Truffoni's
        answer: Sloppy Steak
        points: 400
      - question: The number of coffees you get when you order 55 burgers, 55 fries, 55 tacos, and 55 cokes
        answer: 100 coffees
        points: 500
  - name: On TV
    questions:
      - question: On hit reality show "Summer Loving", this activity left audiences hanging
        answer: Zipline
        points: 100
      - question: Spectrum is planning to drop Corncob TV, which hosts this hit show
        answer: Coffin Flop
        points: 200
      - question: Girls over 60LBs are safe to play with this doll which contains a low, low dose of poison
        answer: Tammy Craps
        points: 300
      - question: This actor played the lead in Detective Crashmore, a movie described by critics as a "cosmic gumbo"
        answer: Santa Claus
        points: 400
      - question: This commercial introduced pop hit Moon River Rock to the world
        answer: Laser Spine Specialists
        points: 500
  - name: Corporate America
    questions:
      - question: You may have issues with employee retention if you schedule meetings during this time.
        answer: Lunch
        points: 100
      - question: Upgrading this piece of office equipment will make your employees say "Santa came early"
        answer: Copier
        points: 200
      - question: This car company put together a focus group to learn more about steering wheel preferences
        answer: Ford
        points: 300
      - question: This high-risk career may cause emotional distress and distracted driving.
        answer: Tables
        points: 400
      - question: IT'S A CHUNKY
        answer: HE IS GOBBLING UP YOUR POINTS
        points: 500
        actual_points: -500
  - name: He Did What???
    questions:
      - question: On the adult ghost tour you can say this one word
        answer: Jizz
        points: 100
      - question: At "Baby of the Year", one of the parents attempted to rig the contest with their own performance of this
        answer: Oral
        points: 200
      - question: Darmine Doggy Doors were invented in response to a pig wearing this
        answer: Richard Nixon Mask
        points: 300
      - question: This store makes defective watches that explode and ruin your date
        answer: TK Jewelers
        points: 400
      - question: Kim Kardashian's head fell off during the collapse of the deck at this popular club
        answer: Club Aqua
        points: 500
